inherit_gem:
  rubocop-inst:
  - rubocop.yml
  - rubocop-rspec.yml

plugins:
  - rubocop-rake

AllCops:
  Exclude:
  - lib/esphome/api/*.rb
  - vendor/**/*

Style/Documentation:
  Enabled: false

RSpec/SpecFilePathFormat:
  CustomTransform:
    ESPHome: esphome
