#!/usr/bin/env ruby
# frozen_string_literal: true

require "optparse"

require "esphome/cli/monitor"

actions = true
log_level = :info
connection_log_level = :warn
device_log_level = :debug
dump_config = false
port = 6053
opts = OptionParser.new do |opts|
  opts.banner = <<~TEXT
    Usage: esphome-monitor ([<uri>] <device_name> | <address> <encryption_key>)

    Example: esphome-monitor http://localhost:6052/ my_device
      If URI is omitted, it defaults to http://localhost:6052/
  TEXT

  opts.on("--port=VALUE", Integer, "Device port to connect to (default 6053)") do |value|
    port = value
  end
  opts.on("--[no-]actions", "Subscribe to Home Assistant actions (default on)") do |v|
    actions = v
  end
  opts.on("--connection-log-level=VALUE", "Connection log level") do |v|
    connection_log_level = v
  end
  opts.on("--device-log-level=VALUE", "Device log level (`fatal` to disable log streaming)") do |v|
    device_log_level = v
  end
  opts.on("--log-level=VALUE", "Monitoring program log level") do |v|
    log_level = v
  end
  opts.on("--dump-config", "Dump device configuration on connect (requires log streaming at info level)") do
    dump_config = true
  end
  opts.on("-h", "--help", "Show this help message") do
    puts opts
    exit
  end
end
opts.parse!

if ARGV.size == 1
  uri = "http://localhost:6052/"
  device_name = ARGV[0]
elsif ARGV.size == 2 && ARGV[0].include?(":")
  uri, device_name = ARGV
elsif ARGV.size == 2
  address, encryption_key = ARGV
else
  warn opts
  exit(-1)
end

if uri
  require "esphome/dashboard"

  begin
    address, encryption_key = ESPHome::Dashboard.address_and_encryption_key(uri, device_name)
  rescue ESPHome::DashboardError => e
    warn e.message
    exit 1
  end
end

device = ESPHome::Device.new(address, encryption_key, port:)

ESPHome::Cli::Monitor.run(device, connection_log_level:, device_log_level:, log_level:, actions:, dump_config:)
